osulp/tresbien

.circleci/config.yml, README.md, app/controllers/reimbursement_requests_controller.rb, app/helpers/reimbursement_request_helper.rb, app/models/reimbursement_request.rb, app/views/reimbursement_requests/show.html.erb, spec/helpers/application_helper_spec.rb, spec/helpers/reimbursement_request_helper_spec.rb, spec/models/reimbursement_request_spec.rb, spec/models/travel_itinerary_spec.rb, spec/spec_helper.rb
=> adds additional tests for coverage

app/assets/stylesheets/navbar.scss, app/assets/stylesheets/reimbursement_request.scss, app/views/reimbursement_requests/_form.html.erb, app/views/reimbursement_requests/_form_total.html.erb
Adjusts size of navigation sidebar so that it looks ok on larger screens and centers the columns in the reimbursement totals card so it doesn't need as much space.
=> Layout changes

app/controllers/application_controller.rb, app/controllers/my_cas_controller.rb, app/controllers/users/sessions_controller.rb, config/routes.rb
=> Uses custom authenticate user method to avoid devise flash messages

app/models/expense_type.rb, app/views/reimbursement_requests/_expense_other_fields.html.erb, config/initializers/rails_admin.rb, yarn.lock
=> adds missing functionality froms and administration

app/views/reimbursement_requests/_expense_other_fields.html.erb, app/views/reimbursement_requests/_form_accounting.html.erb, app/views/reimbursement_requests/_form_airfare.html.erb, app/views/reimbursement_requests/_form_attachments.html.erb, app/views/reimbursement_requests/_form_mileage.html.erb, app/views/reimbursement_requests/_form_other_expenses.html.erb
=> Adds more instructions for the user

app/javascript/packs/reimbursement_request.js, app/javascript/reimbursement_request/form.js, app/models/reimbursement_request.rb, app/views/reimbursement_requests/_accounting_fields.html.erb, app/views/reimbursement_requests/_form.html.erb, app/views/reimbursement_requests/_form_accounting.html.erb, app/views/reimbursement_requests/_form_total.html.erb, app/views/reimbursement_requests/_tab_navigation.html.erb, db/migrate/20171012161127_remove_accounting_total_from_reimbursement_request.rb, db/schema.rb
=> eliminates accounting_total and related functionality

app/javascript/packs/home_table_filters.js, app/views/reimbursement_requests/_table_filters.html.erb
=> Fixes table filters

app/assets/stylesheets/animate.scss, app/assets/stylesheets/application.scss, app/assets/stylesheets/delete_attachment.scss, app/assets/stylesheets/reimbursement_request.scss, app/views/reimbursement_requests/_form_accounting.html.erb, app/views/reimbursement_requests/_form_airfare.html.erb, app/views/reimbursement_requests/_form_attachments.html.erb, app/views/reimbursement_requests/_form_itinerary.html.erb, app/views/reimbursement_requests/_form_mileage.html.erb, app/views/reimbursement_requests/_form_other_expenses.html.erb, app/views/reimbursement_requests/_tab_navigation.html.erb, package.json
=> Adds more instructions to the blue boxes

app/javascript/packs/reimbursement_request.js, app/javascript/reimbursement_request/accounting_row.js, app/javascript/reimbursement_request/basic_row.js, app/javascript/reimbursement_request/expense_other_row.js, app/javascript/reimbursement_request/form.js, app/views/reimbursement_requests/_accounting_fields.html.erb, app/views/reimbursement_requests/_expense_above_per_diem_fields.html.erb, app/views/reimbursement_requests/_expense_airfare_fields.html.erb, app/views/reimbursement_requests/_expense_mileage_fields.html.erb, app/views/reimbursement_requests/_expense_other_fields.html.erb, app/views/reimbursement_requests/_form_accounting.html.erb, app/views/reimbursement_requests/_form_airfare.html.erb, app/views/reimbursement_requests/_form_attachments.html.erb, app/views/reimbursement_requests/_form_mileage.html.erb, app/views/reimbursement_requests/_form_other_expenses.html.erb, app/views/reimbursement_requests/_travel_itinerary_fields.html.erb, db/migrate/20171012163732_add_account_code_to_expense_types.rb, db/schema.rb
connects expense type select to application state
associates other expense to accounting row on UI
fixes #291
=> builds accounting row data dynamically

app/inputs/cs_us_state_select_input.rb, app/javascript/packs/city_state.js, app/views/reimbursement_requests/_expense_mileage_fields.html.erb, db/seeds.rb
Fix #292 
Also updates seeds.rb so that organization does not fail validation
=> Fixes mileage row city state functionality

app/javascript/reimbursement_request/city_row.js, package.json, yarn.lock
=> city row hotel rate updates all of its related itineraries

app/javascript/reimbursement_request/above_per_diem_row.js, app/javascript/reimbursement_request/accounting_row.js, app/javascript/reimbursement_request/basic_row.js, app/javascript/reimbursement_request/city_row.js, app/javascript/reimbursement_request/itinerary_row.js, app/models/travel_itinerary.rb, app/views/reimbursement_requests/_expense_above_per_diem_fields.html.erb, app/views/reimbursement_requests/_expense_airfare_fields.html.erb, app/views/reimbursement_requests/_expense_mileage_fields.html.erb, app/views/reimbursement_requests/_expense_other_fields.html.erb, app/views/reimbursement_requests/_travel_city_fields.html.erb, app/views/reimbursement_requests/_travel_itinerary_fields.html.erb, config/application.rb, spec/models/reimbursement_request_spec.rb
=> updates form to amount fields rendering and bugfixes

app/helpers/reimbursement_request_helper.rb, app/javascript/packs/application.js, app/javascript/packs/before_unload_dialog.js, app/views/reimbursement_requests/_form.html.erb, app/views/reimbursement_requests/_form_itinerary.html.erb
=> Adds an alert message

Gemfile, Gemfile.lock, app/assets/stylesheets/pdf.scss, app/assets/stylesheets/show.scss, app/controllers/reimbursement_requests_controller.rb, app/javascript/packs/application.js, app/javascript/packs/pdf_load_icon.js, app/views/attachments/pdf.html.erb, app/views/reimbursement_requests/show.html.erb
Fix #313 
Also adds a sick loading icon that we didn't even know we needed.
=> Concatenates attachments to end of pdf export, adds loading icon when pdf export is clicked

app/assets/stylesheets/reimbursement_request.scss, app/controllers/reimbursement_requests_controller.rb, app/javascript/packs/reimbursement_request.js, app/javascript/reimbursement_request/above_per_diem_row.js, app/javascript/reimbursement_request/accounting_row.js, app/javascript/reimbursement_request/basic_row.js, app/javascript/reimbursement_request/expense_other_row.js, app/javascript/reimbursement_request/form.js, app/javascript/reimbursement_request/mileage_row.js, app/views/layouts/application.html.erb, app/views/reimbursement_requests/_accounting_fields.html.erb, app/views/reimbursement_requests/_expense_other_fields.html.erb, app/views/reimbursement_requests/_form_itinerary.html.erb, db/migrate/20171024200017_add_client_id_to_accountings.rb, db/schema.rb
=> updates accounting ui for bug fixes and missing functionality

app/helpers/reimbursement_request_helper.rb, app/views/reimbursement_requests/_form_traveller_information.html.erb, config/environments/test.rb, spec/helpers/reimbursement_request_helper_spec.rb
=> sets claimant name on edit page regardless of who is viewing it

app/javascript/reimbursement_request/itinerary_row.js, config/locales/en.yml
=> updates per diem related error messages

app/controllers/reimbursement_requests_controller.rb, config/initializers/rails_admin.rb
=> limits access to requests for admin users and the claimant

app/assets/stylesheets/pdf.scss, app/controllers/reimbursement_requests_controller.rb, app/models/attachment.rb
=> fixes bug with jpeg rendering and image size

app/controllers/reimbursement_requests_controller.rb
=> allow optional content to be loaded

app/assets/stylesheets/reimbursement_request.scss, app/javascript/reimbursement_request/above_per_diem_row.js, app/javascript/reimbursement_request/itinerary_row.js, app/views/reimbursement_requests/_expense_above_per_diem_fields.html.erb, app/views/reimbursement_requests/_form_itinerary.html.erb, config/locales/en.yml
=> adds ability to remove an above per diem expense and update related itinerary day

app/controllers/application_controller.rb, app/javascript/reimbursement_request/mileage_row.js, app/models/account_code.rb, app/models/application_configuration.rb, app/models/expense_mileage.rb, app/views/footer/_footer.html.erb, app/views/reimbursement_requests/_expense_mileage_fields.html.erb, app/views/reimbursement_requests/_form_mileage.html.erb, config/initializers/rails_admin.rb, config/locales/en.yml, db/migrate/20171026142345_add_mileage_rate_to_expense_mileage.rb, db/migrate/20171026143540_create_application_configurations.rb, db/schema.rb, db/seeds.rb, lib/capistrano/tasks/seed.rake, local_env.example.yml
=> moves mileage expense rate to application configuration from db

app/models/account_code.rb, app/models/application_configuration.rb, app/models/description.rb, app/models/organization.rb, config/initializers/rails_admin.rb, db/migrate/20171026155955_add_active_to_organization.rb, db/schema.rb
=> improves model validations

config/cable.yml, config/database.yml, config/secrets.yml, config/webpacker.yml
=> adds staging environment

.circleci/config.yml, .rspec, Gemfile, Gemfile.lock, app/controllers/reimbursement_requests_controller.rb, app/models/reimbursement_request.rb, config/application.rb, config/initializers/devise.rb, config/local_env.example.yml, spec/models/reimbursement_request_spec.rb, spec/spec_helper.rb
=> adds banner export CSV, test, and refactors some code smells

app/models/reimbursement_request.rb
=> adds account code for data export

app/controllers/reimbursement_requests_controller.rb
=> fixes bug with persisting mileage expenses

app/views/reimbursement_requests/_form_accounting.html.erb, app/views/reimbursement_requests/_form_itinerary.html.erb, app/views/reimbursement_requests/_form_other_expenses.html.erb
fixes #358 
fixes #359 
fixes #360 
fixes #361
=> clarifies help text for form sections

app/helpers/reimbursement_request_helper.rb, app/models/reimbursement_request.rb, app/views/reimbursement_requests/show.html.erb, db/migrate/20171227205731_add_invoice_to_reimbursement_request.rb, db/schema.rb
fixes #366 
fixes #367 
fixes #369
=> adds invoice number and banner export field logic

app/controllers/reimbursement_requests_controller.rb, app/javascript/reimbursement_request/form.js, app/javascript/reimbursement_request/itinerary_row.js, app/models/reimbursement_request.rb, app/models/travel_itinerary.rb, app/views/reimbursement_requests/_form_itinerary.html.erb, app/views/reimbursement_requests/_travel_itinerary_fields.html.erb, app/views/reimbursement_requests/show.html.erb, db/migrate/20171229235415_add_percentage_to_travel_itinerary.rb, db/schema.rb
=> calculates percentage reimbursement for travel

Gemfile, Gemfile.lock
=> security updates for gems
